import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  launchBrowser: () => ipcRenderer.invoke('launch-browser'),
  checkBrowserStatus: () => ipcRenderer.invoke('check-browser-status'),
  fetchChats: () => ipcRenderer.invoke('fetch-chats'),
  exportChat: (url: string, characterName: string, reverseTranscript?: boolean, avatarUrl?: string) => ipcRenderer.invoke('export-chat', { url, characterName, reverseTranscript, avatarUrl }),
  runAnalysis: (folderPath: string) => ipcRenderer.invoke('run-analysis', { folderPath }),
  testSelectors: () => ipcRenderer.invoke('test-selectors'),
  openFolder: (path: string) => ipcRenderer.invoke('open-folder', path),
  openPathInExplorer: (path: string) => ipcRenderer.invoke('open-path-in-explorer', path),
  openFile: (path: string) => ipcRenderer.invoke('open-file', path),
  getExportIndex: () => ipcRenderer.invoke('get-export-index'),
  listExportsForChat: (chatId: string) => ipcRenderer.invoke('list-exports-for-chat', chatId),
  readTranscript: (pathOrDir: string, maxLines?: number) => ipcRenderer.invoke('read-transcript', pathOrDir, maxLines),
  readTranscriptPage: (transcriptPath: string, opts: any) => ipcRenderer.invoke('read-transcript-page', transcriptPath, opts),
  readSummary: (summaryPath: string) => ipcRenderer.invoke('read-summary', summaryPath),
  computeInsightsFromTranscript: (transcriptPath: string, maxLines?: number) => ipcRenderer.invoke('compute-insights-from-transcript', transcriptPath, maxLines),
  removeExportEntry: (id: string) => ipcRenderer.invoke('remove-export-entry', id),
  markExportOpened: (id: string) => ipcRenderer.invoke('mark-export-opened', id),
  getProfileDir: () => ipcRenderer.invoke('get-profile-dir'),
  getCharacterCache: () => ipcRenderer.invoke('get-character-cache'),
  getUserProfile: () => ipcRenderer.invoke('get-user-profile'),
  getViewer: () => ipcRenderer.invoke('get-viewer'),
  refreshViewer: () => ipcRenderer.invoke('refresh-viewer-profile'),
  refreshViewerProfile: () => ipcRenderer.invoke('refresh-viewer-profile'),
  getChatsIndex: () => ipcRenderer.invoke('get-chats-index'),
  hydrateChatsMetadata: (urls: string[], limit?: number) => ipcRenderer.invoke('hydrate-chats-metadata', urls, limit),
  cancelHydrate: () => ipcRenderer.invoke('cancel-hydrate'),
  refreshCharactersFromProfile: (sortMode?: string) => ipcRenderer.invoke('refresh-characters-from-profile', sortMode),
  getCharactersIndex: () => ipcRenderer.invoke('get-characters-index'),
  getPersonasIndex: () => ipcRenderer.invoke('get-personas-index'),
  getVoicesIndex: () => ipcRenderer.invoke('get-voices-index'),
  refreshPersonasIndex: (opts?: { maxItems?: number }) => ipcRenderer.invoke('refresh-personas-index', opts),
  refreshVoicesIndex: (opts?: { maxItems?: number }) => ipcRenderer.invoke('refresh-voices-index', opts),
  cancelProfileIndex: () => ipcRenderer.invoke('cancel-profile-index'),
  getSession: () => ipcRenderer.invoke('get-session'),
  saveSession: (patch: any) => ipcRenderer.invoke('save-session', patch),
  refreshCreatorProfiles: (names: string[]) => ipcRenderer.invoke('refresh-creator-profiles', names),
  refreshSidebarScan: () => ipcRenderer.invoke('refresh-sidebar-scan'),
  scrapeFollowersList: (type: 'followers' | 'following') => ipcRenderer.invoke('scrape-followers-list', type),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (partial: any) => ipcRenderer.invoke('save-settings', partial),
  chooseExportRoot: () => ipcRenderer.invoke('choose-export-root'),
  resetBrowserProfile: () => ipcRenderer.invoke('reset-browser-profile'),
  showBrowserView: (rect: { x: number, y: number, width: number, height: number }) => ipcRenderer.invoke('show-browser-view', rect),
  hideBrowserView: () => ipcRenderer.invoke('hide-browser-view'),
  resizeBrowserView: (rect: { x: number, y: number, width: number, height: number }) => ipcRenderer.invoke('resize-browser-view', rect),
  setAlwaysOnTop: (flag: boolean) => ipcRenderer.invoke('set-always-on-top', flag),
  detachBrowser: () => ipcRenderer.invoke('detach-browser'),
  attachBrowser: () => ipcRenderer.invoke('attach-browser'),
  saveLogs: (logs: string[]) => ipcRenderer.invoke('save-logs', logs),
  scrapeCurrentPage: () => ipcRenderer.invoke('scrape-current-page'),
  onScraperLog: (callback: (log: string) => void) => ipcRenderer.on('scraper-log', (_event, value) => callback(value)),
  onAnalysisLog: (callback: (log: string) => void) => ipcRenderer.on('analysis-log', (_event, value) => callback(value)),
  onExportIndexUpdate: (callback: (data: any) => void) => ipcRenderer.on('export-index-updated', (_event, value) => callback(value)),
  onCharactersIndexUpdate: (callback: (data: any) => void) => ipcRenderer.on('characters-index-updated', (_event, value) => callback(value)),
  onPersonasIndexUpdate: (callback: (data: any) => void) => ipcRenderer.on('personas-index-updated', (_event, value) => callback(value)),
  onVoicesIndexUpdate: (callback: (data: any) => void) => ipcRenderer.on('voices-index-updated', (_event, value) => callback(value)),
  onHydrateProgress: (callback: (data: any) => void) => ipcRenderer.on('hydrate-progress', (_event, value) => callback(value)),
  onCreatorHydrateProgress: (callback: (data: any) => void) => ipcRenderer.on('creator-hydrate-progress', (_event, value) => callback(value)),
  onCreatorsIndexUpdate: (callback: (data: any) => void) => ipcRenderer.on('creators-index-updated', (_event, value) => callback(value)),
  onSessionUpdated: (callback: (data: any) => void) => ipcRenderer.on('session-updated', (_event, value) => callback(value)),
  onBrowserDetachedClosed: (callback: () => void) => ipcRenderer.on('browser-detached-closed', () => callback()),
  onQAReport: (callback: (report: any) => void) => ipcRenderer.on('qa-report', (_event, value) => callback(value)),
  
  // Missing methods fixed:
  exportDiagnostics: () => ipcRenderer.invoke('export-diagnostics'),
  cancelJob: () => ipcRenderer.invoke('cancel-job'),
  onJobStatus: (callback: (status: { busy: boolean, current: any }) => void) => ipcRenderer.on('job-status', (_event, value) => callback(value)),
  toggleSnow: (enable: boolean) => ipcRenderer.invoke('toggle-snow', enable),
  runDiagnostics: () => ipcRenderer.invoke('run-diagnostics'),
  testScroll: () => ipcRenderer.invoke('test-scroll'),
  startQAMonitor: (intervalMs?: number) => ipcRenderer.invoke('start-qa-monitor', intervalMs),
  stopQAMonitor: () => ipcRenderer.invoke('stop-qa-monitor'),
  getQAState: () => ipcRenderer.invoke('get-qa-state'),
  qaOverlay: (enable: boolean) => ipcRenderer.invoke('qa-overlay', enable),
  forceScrollProbe: () => ipcRenderer.invoke('force-scroll-probe'),
  saveQASnapshot: () => ipcRenderer.invoke('save-qa-snapshot'),
});
