name: Bug report
description: Report a reproducible problem
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: What happened? Be brief and clear.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Include commands, inputs, and expected vs. actual results.
      placeholder: |
        1. ...
        2. ...
        Expected:
        Actual:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: OS, Node version, app version/tag, and any custom settings.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or attach screenshots.
    validations:
      required: false
