"use strict";
const electron = require("electron");
electron.contextBridge.exposeInMainWorld("electronAPI", {
  launchBrowser: () => electron.ipcRenderer.invoke("launch-browser"),
  checkBrowserStatus: () => electron.ipcRenderer.invoke("check-browser-status"),
  fetchChats: () => electron.ipcRenderer.invoke("fetch-chats"),
  exportChat: (url, characterName, reverseTranscript, avatarUrl) => electron.ipcRenderer.invoke("export-chat", { url, characterName, reverseTranscript, avatarUrl }),
  runAnalysis: (folderPath) => electron.ipcRenderer.invoke("run-analysis", { folderPath }),
  testSelectors: () => electron.ipcRenderer.invoke("test-selectors"),
  openFolder: (path) => electron.ipcRenderer.invoke("open-folder", path),
  openPathInExplorer: (path) => electron.ipcRenderer.invoke("open-path-in-explorer", path),
  openFile: (path) => electron.ipcRenderer.invoke("open-file", path),
  getExportIndex: () => electron.ipcRenderer.invoke("get-export-index"),
  listExportsForChat: (chatId) => electron.ipcRenderer.invoke("list-exports-for-chat", chatId),
  readTranscript: (pathOrDir, maxLines) => electron.ipcRenderer.invoke("read-transcript", pathOrDir, maxLines),
  readTranscriptPage: (transcriptPath, opts) => electron.ipcRenderer.invoke("read-transcript-page", transcriptPath, opts),
  readSummary: (summaryPath) => electron.ipcRenderer.invoke("read-summary", summaryPath),
  computeInsightsFromTranscript: (transcriptPath, maxLines) => electron.ipcRenderer.invoke("compute-insights-from-transcript", transcriptPath, maxLines),
  removeExportEntry: (id) => electron.ipcRenderer.invoke("remove-export-entry", id),
  markExportOpened: (id) => electron.ipcRenderer.invoke("mark-export-opened", id),
  getProfileDir: () => electron.ipcRenderer.invoke("get-profile-dir"),
  getCharacterCache: () => electron.ipcRenderer.invoke("get-character-cache"),
  getUserProfile: () => electron.ipcRenderer.invoke("get-user-profile"),
  getViewer: () => electron.ipcRenderer.invoke("get-viewer"),
  refreshViewer: () => electron.ipcRenderer.invoke("refresh-viewer-profile"),
  refreshViewerProfile: () => electron.ipcRenderer.invoke("refresh-viewer-profile"),
  getChatsIndex: () => electron.ipcRenderer.invoke("get-chats-index"),
  hydrateChatsMetadata: (urls, limit) => electron.ipcRenderer.invoke("hydrate-chats-metadata", urls, limit),
  cancelHydrate: () => electron.ipcRenderer.invoke("cancel-hydrate"),
  refreshCharactersFromProfile: (sortMode) => electron.ipcRenderer.invoke("refresh-characters-from-profile", sortMode),
  getCharactersIndex: () => electron.ipcRenderer.invoke("get-characters-index"),
  getPersonasIndex: () => electron.ipcRenderer.invoke("get-personas-index"),
  getVoicesIndex: () => electron.ipcRenderer.invoke("get-voices-index"),
  refreshPersonasIndex: (opts) => electron.ipcRenderer.invoke("refresh-personas-index", opts),
  refreshVoicesIndex: (opts) => electron.ipcRenderer.invoke("refresh-voices-index", opts),
  cancelProfileIndex: () => electron.ipcRenderer.invoke("cancel-profile-index"),
  getSession: () => electron.ipcRenderer.invoke("get-session"),
  saveSession: (patch) => electron.ipcRenderer.invoke("save-session", patch),
  refreshCreatorProfiles: (names) => electron.ipcRenderer.invoke("refresh-creator-profiles", names),
  refreshSidebarScan: () => electron.ipcRenderer.invoke("refresh-sidebar-scan"),
  scrapeFollowersList: (type) => electron.ipcRenderer.invoke("scrape-followers-list", type),
  getSettings: () => electron.ipcRenderer.invoke("get-settings"),
  saveSettings: (partial) => electron.ipcRenderer.invoke("save-settings", partial),
  chooseExportRoot: () => electron.ipcRenderer.invoke("choose-export-root"),
  resetBrowserProfile: () => electron.ipcRenderer.invoke("reset-browser-profile"),
  showBrowserView: (rect) => electron.ipcRenderer.invoke("show-browser-view", rect),
  hideBrowserView: () => electron.ipcRenderer.invoke("hide-browser-view"),
  resizeBrowserView: (rect) => electron.ipcRenderer.invoke("resize-browser-view", rect),
  setAlwaysOnTop: (flag) => electron.ipcRenderer.invoke("set-always-on-top", flag),
  detachBrowser: () => electron.ipcRenderer.invoke("detach-browser"),
  attachBrowser: () => electron.ipcRenderer.invoke("attach-browser"),
  saveLogs: (logs) => electron.ipcRenderer.invoke("save-logs", logs),
  scrapeCurrentPage: () => electron.ipcRenderer.invoke("scrape-current-page"),
  onScraperLog: (callback) => electron.ipcRenderer.on("scraper-log", (_event, value) => callback(value)),
  onAnalysisLog: (callback) => electron.ipcRenderer.on("analysis-log", (_event, value) => callback(value)),
  onExportIndexUpdate: (callback) => electron.ipcRenderer.on("export-index-updated", (_event, value) => callback(value)),
  onCharactersIndexUpdate: (callback) => electron.ipcRenderer.on("characters-index-updated", (_event, value) => callback(value)),
  onPersonasIndexUpdate: (callback) => electron.ipcRenderer.on("personas-index-updated", (_event, value) => callback(value)),
  onVoicesIndexUpdate: (callback) => electron.ipcRenderer.on("voices-index-updated", (_event, value) => callback(value)),
  onHydrateProgress: (callback) => electron.ipcRenderer.on("hydrate-progress", (_event, value) => callback(value)),
  onCreatorHydrateProgress: (callback) => electron.ipcRenderer.on("creator-hydrate-progress", (_event, value) => callback(value)),
  onCreatorsIndexUpdate: (callback) => electron.ipcRenderer.on("creators-index-updated", (_event, value) => callback(value)),
  onSessionUpdated: (callback) => electron.ipcRenderer.on("session-updated", (_event, value) => callback(value)),
  onBrowserDetachedClosed: (callback) => electron.ipcRenderer.on("browser-detached-closed", () => callback()),
  onQAReport: (callback) => electron.ipcRenderer.on("qa-report", (_event, value) => callback(value)),
  // Missing methods fixed:
  exportDiagnostics: () => electron.ipcRenderer.invoke("export-diagnostics"),
  cancelJob: () => electron.ipcRenderer.invoke("cancel-job"),
  onJobStatus: (callback) => electron.ipcRenderer.on("job-status", (_event, value) => callback(value)),
  toggleSnow: (enable) => electron.ipcRenderer.invoke("toggle-snow", enable),
  runDiagnostics: () => electron.ipcRenderer.invoke("run-diagnostics"),
  testScroll: () => electron.ipcRenderer.invoke("test-scroll"),
  startQAMonitor: (intervalMs) => electron.ipcRenderer.invoke("start-qa-monitor", intervalMs),
  stopQAMonitor: () => electron.ipcRenderer.invoke("stop-qa-monitor"),
  getQAState: () => electron.ipcRenderer.invoke("get-qa-state"),
  qaOverlay: (enable) => electron.ipcRenderer.invoke("qa-overlay", enable),
  forceScrollProbe: () => electron.ipcRenderer.invoke("force-scroll-probe"),
  saveQASnapshot: () => electron.ipcRenderer.invoke("save-qa-snapshot")
});
